require('keymaps/alias')

im('<C-S>', '<esc>:w<cr>a')
nm('<C-S>', ':w<cr>')
im('<C-Q>', '<esc>:q!<cr>')
nm('<C-Q>', ':q!<cr>')
nm('nt', '<cmd>Explore .<cr>')
nm('ct', '<cmd>bd %<cr><cmd>bp<cr>')
nm('gp', '<cmd>bp<cr>')
nm('gn', '<cmd>bn<cr>')
nm('<leader><Up>', '<C-W>k')
nm('<leader><Down>', '<C-W>j')
nm('<leader><Right>', '<C-W>l')
nm('<leader><Left>', '<C-W>h')
nm('<leader>h', ':sp<cr>')
nm('<leader>v', ':vs<cr>')
nm('jk' ,'<esc>')
nm('x', '_x')
nm('<leader>r', ':luafile %<cr>')
